version: "3.8"
networks: 
    teste_backend:
        driver: bridge
services:
    db:
        image: postgres
        networks:
            teste_backend:
                aliases:
                - teste_backend_db
        restart: always
        volumes: 
          - ./data:/var/lib/postgresql/data
        ports:
          - 5455:5432
        environment:
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: postgresDB
            POSTGRES_USER: admin
    web:
        build: ./server
        container_name: web
        networks:
            teste_backend:
                aliases:
                - teste_backend_web
        depends_on:
            - db
        ports:
            - "8080:80"
        volumes:
            - ./server:/var/www/html